config/routes.rb
Odometers::Application.routes.draw do
  resources :purpose_defs

  resources :purposes

  resources :trips

  resources :vehicles

end

app/controllers/purposes_controller.rb
class PurposesController < ApplicationController
  # GET /purposes
  # GET /purposes.xml
  def index
    @purposes = Purpose.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @purposes }
    end
  end

  # GET /purposes/1
  # GET /purposes/1.xml
  def show
    @purpose = Purpose.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @purpose }
    end
  end

  # GET /purposes/new
  # GET /purposes/new.xml
  def new
    @purpose = Purpose.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @purpose }
    end
  end

  # GET /purposes/1/edit
  def edit
    @purpose = Purpose.find(params[:id])
  end

  # POST /purposes
  # POST /purposes.xml
  def create
    @purpose = Purpose.new(params[:purpose])

    respond_to do |format|
      if @purpose.save
        format.html { redirect_to(@purpose, :notice => 'Purpose was successfully created.') }
        format.xml  { render :xml => @purpose, :status => :created, :location => @purpose }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @purpose.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /purposes/1
  # PUT /purposes/1.xml
  def update
    @purpose = Purpose.find(params[:id])

    respond_to do |format|
      if @purpose.update_attributes(params[:purpose])
        format.html { redirect_to(@purpose, :notice => 'Purpose was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @purpose.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /purposes/1
  # DELETE /purposes/1.xml
  def destroy
    @purpose = Purpose.find(params[:id])
    @purpose.destroy

    respond_to do |format|
      format.html { redirect_to(purposes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/purposes_helper.rb
module PurposesHelper
end

app/views/purposes/_form.html.erb
<%= form_for(@purpose) do |f| %>
  <% if @purpose.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purpose.errors.count, "error") %> prohibited this purpose from being saved:</h2>

      <ul>
      <% @purpose.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_id %><br />
    <%= f.text_field :trip_id %>
  </div>
  <div class="field">
    <%= f.label :purpose_id %><br />
    <%= f.text_field :purpose_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purposes/edit.html.erb
<h1>Editing purpose</h1>

<%= render 'form' %>

<%= link_to 'Show', @purpose %> |
<%= link_to 'Back', purposes_path %>

app/views/purposes/index.html.erb
<h1>Listing purposes</h1>

<table>
  <tr>
    <th>Trip</th>
    <th>Purpose</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purposes.each do |purpose| %>
  <tr>
    <td><%= purpose.trip_id %></td>
    <td><%= purpose.purpose_id %></td>
    <td><%= link_to 'Show', purpose %></td>
    <td><%= link_to 'Edit', edit_purpose_path(purpose) %></td>
    <td><%= link_to 'Destroy', purpose, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purpose', new_purpose_path %>

app/views/purposes/new.html.erb
<h1>New purpose</h1>

<%= render 'form' %>

<%= link_to 'Back', purposes_path %>

app/views/purposes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Trip:</b>
  <%= @purpose.trip_id %>
</p>

<p>
  <b>Purpose:</b>
  <%= @purpose.purpose_id %>
</p>


<%= link_to 'Edit', edit_purpose_path(@purpose) %> |
<%= link_to 'Back', purposes_path %>