config/routes.rb
Odometers::Application.routes.draw do
  resources :purpose_defs

  resources :purposes

  resources :trips

  resources :vehicles

end

app/models/purpose_def.rb
class PurposeDef < ActiveRecord::Base
end

app/controllers/purpose_defs_controller.rb
class PurposeDefsController < ApplicationController
  # GET /purpose_defs
  # GET /purpose_defs.xml
  def index
    @purpose_defs = PurposeDef.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @purpose_defs }
    end
  end

  # GET /purpose_defs/1
  # GET /purpose_defs/1.xml
  def show
    @purpose_def = PurposeDef.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @purpose_def }
    end
  end

  # GET /purpose_defs/new
  # GET /purpose_defs/new.xml
  def new
    @purpose_def = PurposeDef.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @purpose_def }
    end
  end

  # GET /purpose_defs/1/edit
  def edit
    @purpose_def = PurposeDef.find(params[:id])
  end

  # POST /purpose_defs
  # POST /purpose_defs.xml
  def create
    @purpose_def = PurposeDef.new(params[:purpose_def])

    respond_to do |format|
      if @purpose_def.save
        format.html { redirect_to(@purpose_def, :notice => 'Purpose def was successfully created.') }
        format.xml  { render :xml => @purpose_def, :status => :created, :location => @purpose_def }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @purpose_def.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /purpose_defs/1
  # PUT /purpose_defs/1.xml
  def update
    @purpose_def = PurposeDef.find(params[:id])

    respond_to do |format|
      if @purpose_def.update_attributes(params[:purpose_def])
        format.html { redirect_to(@purpose_def, :notice => 'Purpose def was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @purpose_def.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /purpose_defs/1
  # DELETE /purpose_defs/1.xml
  def destroy
    @purpose_def = PurposeDef.find(params[:id])
    @purpose_def.destroy

    respond_to do |format|
      format.html { redirect_to(purpose_defs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/purpose_defs_helper.rb
module PurposeDefsHelper
end

app/views/purpose_defs/_form.html.erb
<%= form_for(@purpose_def) do |f| %>
  <% if @purpose_def.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purpose_def.errors.count, "error") %> prohibited this purpose_def from being saved:</h2>

      <ul>
      <% @purpose_def.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purpose_defs/edit.html.erb
<h1>Editing purpose_def</h1>

<%= render 'form' %>

<%= link_to 'Show', @purpose_def %> |
<%= link_to 'Back', purpose_defs_path %>

app/views/purpose_defs/index.html.erb
<h1>Listing purpose_defs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purpose_defs.each do |purpose_def| %>
  <tr>
    <td><%= purpose_def.name %></td>
    <td><%= purpose_def.description %></td>
    <td><%= link_to 'Show', purpose_def %></td>
    <td><%= link_to 'Edit', edit_purpose_def_path(purpose_def) %></td>
    <td><%= link_to 'Destroy', purpose_def, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purpose def', new_purpose_def_path %>

app/views/purpose_defs/new.html.erb
<h1>New purpose_def</h1>

<%= render 'form' %>

<%= link_to 'Back', purpose_defs_path %>

app/views/purpose_defs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @purpose_def.name %>
</p>

<p>
  <b>Description:</b>
  <%= @purpose_def.description %>
</p>


<%= link_to 'Edit', edit_purpose_def_path(@purpose_def) %> |
<%= link_to 'Back', purpose_defs_path %>